# Numpy
- based on https://github.com/mephistopheies/mlworkshop39_042017/blob/master/0_python_intro/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F.ipynb

<img src="trainings1.jpg" />

## Task 0
- import numpy

In [1]:
import numpy as np

## Task 1
- print version of numpy

In [2]:
print (np.version.full_version)

1.15.4


## Task 2
- create 1d vector of zeros of size 10

In [3]:
a = np.zeros((1,10))
print (a)
print (a.size)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
10


In [4]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Task 3
- create 1d vector filled with ones of size 10

In [5]:
a = np.ones((1,10))
print (a)
print (a.size)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
10


## Task 4
- create 1d vector filled with ones of size 10,

In [6]:
a = np.zeros((10,))
print (a)
print (a.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)


## Task 5
- crete 1d vector filled with numbers from 10 to 49

In [7]:
a = np.array((range(10,50)))
print (a)
print (a.size)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
40


## Task 6
- create any 1d vector, then reverse it, such that last element will be on the first position

In [8]:
a = np.array((range(10,50)))
a = np.flip(a)
print (a)
print (a.size)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
40


## Task 7
- create 2d 3x3 array / matrix, filled with numbers from 0 to 8

In [9]:
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Task 8
- create 3x3 matrix filled with ones

In [10]:
a = np.ones((1,9)).reshape(3,3)
print (a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
a= np.full((3,3),1)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## Task 9
- create 3x3 matrix filled with random numbers

In [12]:
e = np.random.random((3,3))
e

array([[0.55738881, 0.89029387, 0.80307691],
       [0.68098605, 0.61154305, 0.28631332],
       [0.61679116, 0.77192261, 0.91308787]])

In [13]:
a = np.random.randint(0,99,(3,3))
a

array([[ 2, 77, 19],
       [90, 64, 39],
       [58, 95, 40]])

## Task 10
- create 3x3x3 array filled with random numbers

In [14]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Task 11
- create 10x10 matrix filled with random numbers and find minimal and maximal elements

In [15]:
a = np.random.randint(0,99,(10,10))
print(a)
print(a.max())
print(a.min())

[[61  6 65 67 59 21  8 71 73 49]
 [46 48  4 72 45 19 79 86 81 27]
 [52 61 19 98 95 44 17 42 30 76]
 [23 84 14 79 41 98  1 41 23 80]
 [58 41 79 86 36 63 51 51  7 50]
 [21 80 39 61 84 49 52 65 95 17]
 [48  2 46 93 95 74  0 90 67 28]
 [52  1 72 27 56  3 82 40 88 22]
 [53  5 42 69 64 81 59 80  2 50]
 [44  4  6 56 53 86  2 68 12 64]]
98
0


## Task 12
- create a random 1d vector of size 30 and find average of them

In [16]:
a = np.random.randint(0,150,(30))
print(a)
a.mean()

[142 149  50 116  61 130  78   8  76 115   0  62  27  48 125  47 136  69
  23  93  42  57  27  92  18  10   2  68 136  13]


67.33333333333333

## Task 13
- create 5x5 matrix, which has ones on a "frame" and zeros inside

In [17]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Task 14
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **don't use** `tile` funtion

In [18]:
board = np.zeros((8,8), np.int32)
board[::2,::2] = 1
board[1::2,1::2] = 1
board

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)

## Task 15
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **use** `tile` funtion

In [19]:
a = np.array([[1,0],[0,1]])
b = np.tile(a, (4,4))
b

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Task 16
- create two random matrices 5x3 and 3x2
- multiply them

In [20]:
a = np.random.randint(0,99,(5,3))
b = np.random.randint(0,99,(3,2))
print(np.dot(a,b))

[[ 4835 12144]
 [ 1110  4638]
 [ 6440 12112]
 [ 4309 10672]
 [ 2952 10474]]


## Task 17
- create array of size 100 filled with random numbers from 0 to 10
- chenge sign of all numbers which are in a range between 3 and 8

In [72]:
a = np.random.randint(0,11,(100,))
a = np.where(a>2,-a,a)
a

array([  2,  -9,  -8,  -6,   1,  -8,   0,  -3,  -3,  -5,   1,  -8,  -5,
         1,  -6,   1,  -3,   2,  -7,  -5,  -4,   0,  -5,  -7,  -7,  -6,
        -4, -10,  -9,   2,  -7,  -3,   1, -10,   0,  -7,  -5,  -3,   1,
        -7,  -9,  -5,  -3,   2,  -6,  -9,   0,  -6,  -4,  -9,   1,  -6,
         0,   1,  -6,   2, -10,  -3,  -7,   0,  -6,  -6,  -9,  -9,   0,
        -4,  -3,   2,  -3,  -3,  -7,  -9,  -6,   1,   2,  -8,  -5,  -6,
        -8,  -9,   0,   0,   0,   0,   0,  -9,   0,  -8,   0,  -6,  -6,
         1,  -6,  -7,   2,  -6,  -6,  -8,  -8,  -7])

## Task 18
- create a matrix 5x5 such that each row would be a 1d array filled with numbers from 0 to 4

In [101]:
a = np.array([0,1,2,3,4])
b = np.tile(a,5)
b

TypeError: tile() got an unexpected keyword argument 'axis'

## Task 19
- create 1d vector of size 100 filled with random values from range 0-1, excluding boundary values (no exact 0/1)

In [88]:
e = np.random.random((1,100))
e

array([[0.20315534, 0.32667456, 0.05062136, 0.49149482, 0.49763571,
        0.57649548, 0.79716313, 0.34395435, 0.89988739, 0.38940649,
        0.99188683, 0.97418449, 0.33664293, 0.09422242, 0.34693749,
        0.66986715, 0.74643474, 0.83282367, 0.07385759, 0.84127598,
        0.61564859, 0.86251976, 0.15089326, 0.0424122 , 0.22841063,
        0.53548723, 0.23692808, 0.2478003 , 0.48946007, 0.78751275,
        0.71431571, 0.34285135, 0.24537199, 0.29680687, 0.33193275,
        0.8219763 , 0.86509874, 0.65112983, 0.44262418, 0.44728111,
        0.29664627, 0.35929438, 0.76159454, 0.73228784, 0.72646149,
        0.53021131, 0.66150906, 0.23994758, 0.99520745, 0.7600676 ,
        0.01956677, 0.70790765, 0.3181264 , 0.40729166, 0.80107538,
        0.21000494, 0.28565326, 0.60059525, 0.69790722, 0.39927985,
        0.18830058, 0.49149192, 0.39132568, 0.57115501, 0.99237671,
        0.29373159, 0.14408441, 0.80872112, 0.2970223 , 0.64334198,
        0.9381348 , 0.51330444, 0.60458513, 0.60

## Task 20
- create a 10x2 random matrix filled with number from range 0-100
- consider it as points in Cartesian plain
- convert to polar system of coordinates

In [98]:
a = np.random.randint(0,101,(10,2))
print (a)
x,y = a[:,0],a[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print (r)
print (t)

[[ 6 30]
 [56 87]
 [85 10]
 [95 16]
 [54  4]
 [61 10]
 [61 93]
 [45 32]
 [83 77]
 [33 71]]
[ 30.59411708 103.46496992  85.58621384  96.33794683  54.14794548
  61.81423784 111.22050171  55.21775077 113.21660656  78.29431652]
[1.37340077 0.99887813 0.11710874 0.16685516 0.07393904 0.16248911
 0.99027488 0.61814423 0.74791573 1.13571238]


## Task 21
- create random 13x13 matrix, replace maximal element to zero

In [122]:
a = np.random.randint(0,101,(13,13))
print(a)
print(a.max())
a[a==a.max()]=0
a

[[ 73  21  20  18  70  92  34  10  77  83  75  42   2]
 [ 87  74   7  23  12  24  56  81  36  78  15  70  97]
 [ 26  62  34  51  92  80  40  51  65  20  77  75  63]
 [ 71  47  18  44  99  50  22   4  65  26  11  96  10]
 [ 49  25  90  31  85  23  53   0   9  18  83  55  54]
 [ 49  16  56  33  94  41  64  67  79   6  67  30   8]
 [ 67  37  87  82  32  42  83  61  63  59   6  22   6]
 [ 22   3  81  75  75  73  97  49  59  81  28   8  91]
 [ 96  14  24  58  86  74  57  65  94  38  95   3  46]
 [ 20  25  73  93  46  26  43  84  67  92  13  13  75]
 [ 11 100  21  98  67  44  78  88  28  38   4  71  73]
 [ 40  32  69  33  37   1  67  59  81  54  93  35  69]
 [  6  11  91  11  81  55  79  59  33  22   2  28  72]]
100


array([[73, 21, 20, 18, 70, 92, 34, 10, 77, 83, 75, 42,  2],
       [87, 74,  7, 23, 12, 24, 56, 81, 36, 78, 15, 70, 97],
       [26, 62, 34, 51, 92, 80, 40, 51, 65, 20, 77, 75, 63],
       [71, 47, 18, 44, 99, 50, 22,  4, 65, 26, 11, 96, 10],
       [49, 25, 90, 31, 85, 23, 53,  0,  9, 18, 83, 55, 54],
       [49, 16, 56, 33, 94, 41, 64, 67, 79,  6, 67, 30,  8],
       [67, 37, 87, 82, 32, 42, 83, 61, 63, 59,  6, 22,  6],
       [22,  3, 81, 75, 75, 73, 97, 49, 59, 81, 28,  8, 91],
       [96, 14, 24, 58, 86, 74, 57, 65, 94, 38, 95,  3, 46],
       [20, 25, 73, 93, 46, 26, 43, 84, 67, 92, 13, 13, 75],
       [11,  0, 21, 98, 67, 44, 78, 88, 28, 38,  4, 71, 73],
       [40, 32, 69, 33, 37,  1, 67, 59, 81, 54, 93, 35, 69],
       [ 6, 11, 91, 11, 81, 55, 79, 59, 33, 22,  2, 28, 72]])

In [124]:
a = np.random.randint(0,101,(13,13))
print(a)
print(a.max())
b = np.minimum(a,a.max())#manimum replaces everything to less than pr eqal to a.max()
b

[[ 11  60  24  21  60  26  41  43  16  70  18  22  63]
 [ 77  36  91  97  63  30  26  37  66  59   6  40  82]
 [ 47  30  84  66   1  98  77  90  65   0  41  98   0]
 [ 78  33  34  23  64  97  40  57   8  82  58  93  43]
 [  9  28   7  30   1  50  77  12  23  32   7  74   8]
 [ 49  34  61  17  75  31  65  58  10  66  10  32  19]
 [ 16  98  73  45  41  16  18  55  45  23  62  91  59]
 [ 74  64  26  57  41  65  89 100  95  30  50  42   4]
 [ 37  11  15  34  87  64  37  35  48  36  53  77  85]
 [ 26  86  20  57  26  14  75  64  55  39  38   2  25]
 [ 89  62 100  34   3  63  32  14  47  49  55  40 100]
 [ 47   0  56  92  75  70  73   6  46  66  10  64  29]
 [ 73  82  30  63  98  26   1  86  77  78  91  72  56]]
100


array([[ 11,  60,  24,  21,  60,  26,  41,  43,  16,  70,  18,  22,  63],
       [ 77,  36,  91,  97,  63,  30,  26,  37,  66,  59,   6,  40,  82],
       [ 47,  30,  84,  66,   1,  98,  77,  90,  65,   0,  41,  98,   0],
       [ 78,  33,  34,  23,  64,  97,  40,  57,   8,  82,  58,  93,  43],
       [  9,  28,   7,  30,   1,  50,  77,  12,  23,  32,   7,  74,   8],
       [ 49,  34,  61,  17,  75,  31,  65,  58,  10,  66,  10,  32,  19],
       [ 16,  98,  73,  45,  41,  16,  18,  55,  45,  23,  62,  91,  59],
       [ 74,  64,  26,  57,  41,  65,  89, 100,  95,  30,  50,  42,   4],
       [ 37,  11,  15,  34,  87,  64,  37,  35,  48,  36,  53,  77,  85],
       [ 26,  86,  20,  57,  26,  14,  75,  64,  55,  39,  38,   2,  25],
       [ 89,  62, 100,  34,   3,  63,  32,  14,  47,  49,  55,  40, 100],
       [ 47,   0,  56,  92,  75,  70,  73,   6,  46,  66,  10,  64,  29],
       [ 73,  82,  30,  63,  98,  26,   1,  86,  77,  78,  91,  72,  56]])

## Task 22
- create two 1d arrays with random values
- make a Cauchy matrix from them $C (C_{ij} = \frac{1}{x_i - y_j})$

In [127]:
a = np.random.randint(0,101,(2,2))
b = np.random.randint(0,101,(2,2))
1.0/(x.reshape((-1,1))-y)

array([[-0.04166667, -0.01234568, -0.25      , -0.1       ,  0.5       ,
        -0.25      , -0.01149425, -0.03846154, -0.01408451, -0.01538462],
       [ 0.03846154, -0.03225806,  0.02173913,  0.025     ,  0.01923077,
         0.02173913, -0.02702703,  0.04166667, -0.04761905, -0.06666667],
       [ 0.01818182, -0.5       ,  0.01333333,  0.01449275,  0.01234568,
         0.01333333, -0.125     ,  0.01886792,  0.125     ,  0.07142857],
       [ 0.01538462,  0.125     ,  0.01176471,  0.01265823,  0.01098901,
         0.01176471,  0.5       ,  0.01587302,  0.05555556,  0.04166667],
       [ 0.04166667, -0.03030303,  0.02272727,  0.02631579,  0.02      ,
         0.02272727, -0.02564103,  0.04545455, -0.04347826, -0.05882353],
       [ 0.03225806, -0.03846154,  0.01960784,  0.02222222,  0.01754386,
         0.01960784, -0.03125   ,  0.03448276, -0.0625    , -0.1       ],
       [ 0.03225806, -0.03846154,  0.01960784,  0.02222222,  0.01754386,
         0.01960784, -0.03125   ,  0.03448276

## Task 23
- create an array of random `float` numbers and convert it to `int`

In [132]:
a = np.random.uniform(low=0.,high=100.,size=(2,2))
a.astype(int)

array([[82, 39],
       [96, 75]])

## Task 24
- create 1d array of numbers from 0 to 15
- put each of them in random positions inside 4x4 matrix

In [149]:
a = np.random.randint(0,15,(1,16))
print (a)
print (a.reshape(4,4, order='F'))

[[11 12 12  6 13  6  7  0 13  8  8 14 12  6  8 10]]
[[11 13 13 12]
 [12  6  8  6]
 [12  7  8  8]
 [ 6  0 14 10]]


## Task 25
- create random 100x50 matrix
- deduct avarage of each row from correspondatn rows

In [ ]:
a = np.random.randint(0,101,(100,50))
a

## Task 26 
- create random 10x10 matrix
- extract diagonal elements and put them into 1d array

In [153]:
a = np.random.randint(0,101,(10,10))
print (a)
print (a.diagonal())

[[88 66 47 60 65 62 42 53 58  5]
 [69 44 28  7 81  0 33 65 59 91]
 [ 9 45  0 24 40 70 35 84 14 75]
 [11 80 22 62 12 41 51 16 93 25]
 [12 23 73 93 25  4  5 28 47 28]
 [49 83 15 94 11 37 96  8 11 43]
 [42 65 20 26 47 35 97 28 42 32]
 [86 72 59 29 45 29 17  6 60 89]
 [32 55 29 67 38 60 30 83 53 21]
 [71 33 82 25 26 21 66 67 89  0]]
[88 44  0 62 25 37 97  6 53  0]


## Task 27
- given a vector `[1, 2, 3, 4, 5]`
- build a new vertor with three zeros between each element

In [177]:
x= np.arange(1,6)
m=3
pos=np.repeat(range(1,len(x)),m)
np.insert(x,pos,0)

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

In [176]:
x= np.arange(1,6)
b=np.zeros(1+(m+1)*(x.size-1),dtype=x.dtype)
b[::m+1]=x
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])